#!/usr/bin/env python3
"""AD103 capstone - check the inverter YOU drew.

Reads the netlist XSchem just wrote from xschem/my_inverter.sch, tells you
what is wrong with it in words if anything is, and if nothing is, simulates it
and compares its switching threshold with the reference inverter's.

    python3 src/check_mine.py
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from inv import RESULTS, analyse, read_wrdata  # noqa: E402

LAB = Path(__file__).resolve().parent.parent
NETLIST = LAB / "xschem" / "simulation" / "my_inverter.spice"
REF_VM = 0.838027

text = NETLIST.read_text()
devices = [ln for ln in text.splitlines() if re.match(r"^X\S+\s", ln)]
nfets = [ln for ln in devices if "nfet_01v8" in ln]
pfets = [ln for ln in devices if "pfet_01v8" in ln]

print()
print("  WHAT YOU DREW")
for ln in devices:
    print(f"    {ln.strip()}")
if not devices:
    print("    (no device lines at all)")

problems: list[str] = []

# --- 1. is anything there? --------------------------------------------------
if len(nfets) != 1:
    problems.append(f"the netlist has {len(nfets)} nfet_01v8, and an inverter "
                    f"needs exactly 1. Press Shift-I, open the sky130A library, "
                    f"then sky130_fd_pr, and search for nfet_01v8*.sym")
if len(pfets) != 1:
    problems.append(f"the netlist has {len(pfets)} pfet_01v8, and an inverter "
                    f"needs exactly 1")

# --- 2. unit suffixes -------------------------------------------------------
for ln in devices:
    for attr in ("W", "L"):
        m = re.search(rf"\b{attr}=([^\s]+)", ln)
        if m and re.search(r"[a-zA-Z]$", m.group(1)):
            problems.append(f"{attr}={m.group(1)} carries a unit suffix. SKY130 "
                            f"wants plain microns: {attr}=1, never {attr}=1u")

# --- 3. invented net names = an unconnected pin -----------------------------
invented = sorted(set(re.findall(r"\bnet\d+\b", text)))
if invented:
    problems.append(f"the netlist contains invented net names "
                    f"({', '.join(invented[:4])}). XSchem makes one of those up "
                    f"for every pin that is not connected to anything. Find the "
                    f"wire that does not quite land on its pin - Shift-W snaps "
                    f"to the nearest one")

# --- 4. the four nodes on each device line ----------------------------------
# Order on a sky130 device line is: drain gate source body.
def nodes(line: str) -> list[str]:
    return line.split()[1:5]

if len(nfets) == 1:
    d, g, s, b = nodes(nfets[0])
    if s.lower() not in ("0", "gnd", "vss"):
        problems.append(f"the NMOS source is on '{s}'. It belongs on ground - "
                        f"that is the third node on the device line")
    if b.lower() not in ("0", "gnd", "vss"):
        problems.append(f"the NMOS body is on '{b}'. It belongs on ground too - "
                        f"fourth node")
if len(pfets) == 1:
    d, g, s, b = nodes(pfets[0])
    if s.lower() not in ("vdd", "vpwr"):
        problems.append(f"the PMOS source is on '{s}'. It belongs on vdd - "
                        f"third node. A PMOS whose source is grounded is not "
                        f"a pull-up, and nothing will warn you")
    if b.lower() not in ("vdd", "vpwr"):
        problems.append(f"the PMOS body is on '{b}'. It belongs on vdd too - "
                        f"fourth node")
if len(nfets) == 1 and len(pfets) == 1:
    dn, gn = nodes(nfets[0])[:2]
    dp, gp = nodes(pfets[0])[:2]
    if dn != dp:
        problems.append(f"the two drains are on different nets ('{dn}' and "
                        f"'{dp}'). They have to be the same net - that net is "
                        f"the output")
    if gn != gp:
        problems.append(f"the two gates are on different nets ('{gn}' and "
                        f"'{gp}'). They have to be the same net - that net is "
                        f"the input")

if problems:
    print()
    print("FAIL")
    for p in problems:
        print(f"  - {p}")
    sys.exit(1)

# --- 5. it looks right. Does it behave? -------------------------------------
print()
print("  The netlist is wired like an inverter. Simulating it.")
deck = LAB / "results" / "my_inverter_tb.spice"
deck.parent.mkdir(exist_ok=True)
deck.write_text(f"""* generated by src/check_mine.py - your schematic, in a testbench
.lib $PDK_ROOT/sky130A/libs.tech/ngspice/sky130.lib.spice.tt.red tt
Vdd vdd 0 1.8
Vin in 0 0
{nfets[0].strip()}
{pfets[0].strip()}
.control
dc Vin 0 1.8 0.001
wrdata results/my_vtc.txt v({nodes(nfets[0])[0]})
.endc
.end
""")
subprocess.run(["ngspice", "-b", str(deck.relative_to(LAB))], cwd=LAB,
               stdout=open(LAB / "results" / "my_inverter_tb.log", "w"),
               stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL, check=False)

data = RESULTS / "my_vtc.txt"
if not data.exists() or data.stat().st_size == 0:
    print()
    print("FAIL  ngspice produced no data. The first Error line in")
    print("      results/my_inverter_tb.log is the real one:")
    for line in (LAB / "results" / "my_inverter_tb.log").read_text().splitlines():
        if line.startswith("Error on line") or "could not find" in line:
            print(f"        {line.strip()}")
    sys.exit(1)

dd = read_wrdata(data)
try:
    v = analyse(dd[:, 0], dd[:, 1])
except SystemExit as exc:
    print(f"\nFAIL  {exc}")
    sys.exit(1)

print()
print("  YOUR INVERTER")
print(f"    V_out(0.0 V)          {v.vout[0]:12.6f} V")
print(f"    V_out(1.8 V)          {v.vout[-1]:12.6e} V")
print(f"    switching threshold   {v.vm:12.6f} V")
print(f"    gain at V_M           {v.gain:12.4f}")
print(f"    noise margins H / L   {v.nmh:8.4f} / {v.nml:.4f} V")

wn = re.search(r"\bW=([\d.]+)", nfets[0]).group(1)
wp = re.search(r"\bW=([\d.]+)", pfets[0]).group(1)
print()
if abs(float(wn) - 1) < 1e-9 and abs(float(wp) - 1) < 1e-9:
    if abs(v.vm - REF_VM) < 0.001:
        print(f"PASS  Wn = Wp = 1 um, and your V_M is {v.vm:.6f} V against the")
        print(f"      reference {REF_VM:.6f} V. You drew the same inverter the")
        print(f"      shipped deck describes, and it behaves identically.")
        sys.exit(0)
    print(f"FAIL  Wn = Wp = 1 um should give V_M = {REF_VM:.6f} V and yours is")
    print(f"      {v.vm:.6f} V. Check L on both devices - it should be 0.15.")
    sys.exit(1)

print(f"PASS  it inverts, rail to rail, with V_M = {v.vm:.6f} V.")
print(f"      Your sizes are Wn = {wn}, Wp = {wp}. The shipped reference uses")
print(f"      Wn = Wp = 1 and gets {REF_VM:.6f} V - so if you want to compare")
print(f"      against it directly, draw those sizes too.")
sys.exit(0)
