#!/usr/bin/env python3
"""AD103 Lab 01 - check the schematic YOU drew.

Reads the netlist XSchem just wrote from xschem/my_probe.sch, says in words
what is wrong with it if anything is, and if nothing is, simulates it and
compares your drain current with the reference.

Nothing here is magic. It checks the five things a first schematic actually
gets wrong, in the order they happen.

    python3 src/check_mine.py
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

LAB = Path(__file__).resolve().parent.parent
NETLIST = LAB / "xschem" / "simulation" / "my_probe.spice"
RESULTS = LAB / "results"

# Measured on hpretl/iic-osic-tools:2026.08, from the XSchem netlist - which
# carries the diffusion parasitics the symbol computes, so it is 0.02 % below
# the bare hand-written deck's number.
REF_W = "2"
REF_L = "0.15"
REF_ID_UA = 1030.4200
TOL_UA = 0.5

if not NETLIST.exists():
    print(f"FAIL\n  - no netlist at {NETLIST}")
    print("  - run 'make mine', which netlists the schematic first")
    sys.exit(1)

text = NETLIST.read_text()
devices = [ln for ln in text.splitlines() if re.match(r"^X\S+\s", ln)]

print()
print("  WHAT YOU DREW")
if devices:
    for ln in devices:
        print(f"    {ln.strip()}")
else:
    print("    (no device lines at all)")

problems: list[str] = []

# --- 1. is there a transistor? ---------------------------------------------
nfets = [ln for ln in devices if "nfet_01v8" in ln]
if len(nfets) == 0:
    problems.append("the netlist has no nfet_01v8. Press Shift-I, click the "
                    "sky130A line in the left pane, open sky130_fd_pr, and put "
                    "nfet_01v8*.sym in the Search box. It is a glob, so plain "
                    "'nfet' matches nothing")
elif len(nfets) > 1:
    problems.append(f"the netlist has {len(nfets)} transistors and this lab "
                    f"wants exactly one. Select the extra and press Delete")

# --- 2. unit suffixes on W or L --------------------------------------------
for ln in devices:
    for attr in ("W", "L"):
        m = re.search(rf"\b{attr}=([^\s]+)", ln)
        if m and re.search(r"[a-zA-Z]$", m.group(1)):
            problems.append(
                f"{attr}={m.group(1)} carries a unit suffix. SKY130 wants plain "
                f"micron numbers - {attr}={m.group(1)[:-1]}, not "
                f"{m.group(1)}. Run 'make wrong-units' to see what ngspice does "
                f"about it")

# --- 3. invented net names = a wire that did not land ----------------------
invented = sorted(set(re.findall(r"\bnet\d+\b", text)))
if invented:
    problems.append(
        f"the netlist contains {', '.join(invented)}. XSchem invents a name "
        f"like that for every pin connected to nothing, and it does it silently. "
        f"Find the wire that ends near a pin instead of on it. Shift-W snaps "
        f"the START of a wire onto the nearest pin - for the far end you have to "
        f"keep Shift held down for the click that finishes the wire, or draw the "
        f"wire the other way round. Run 'make unconnected' to see what a floating "
        f"gate does to the answer")

# --- 4. the four node names ------------------------------------------------
if len(nfets) == 1:
    d, g, s, b = nfets[0].split()[1:5]
    if d != "d":
        problems.append(f"the drain is on net '{d}', and the lab's drain net is "
                        f"called 'd'. Device line order is drain, gate, source, "
                        f"body - the drain is the FIRST node")
    if g != "g":
        problems.append(f"the gate is on net '{g}', and the lab's gate net is "
                        f"called 'g'. The gate is the second node")
    if s not in ("0", "gnd"):
        problems.append(f"the source is on net '{s}' and belongs on ground. "
                        f"Third node")
    if b not in ("0", "gnd"):
        problems.append(f"the body is on net '{b}' and belongs on ground too. "
                        f"Fourth node - it is the middle pin on the right edge "
                        f"of the symbol, and it is the one everybody forgets")

if problems:
    print()
    print("FAIL")
    for p in problems:
        print(f"  - {p}")
    sys.exit(1)

# --- 5. it is wired right. Does it give the right number? ------------------
print()
print("  Wired correctly. Simulating it.")
RESULTS.mkdir(exist_ok=True)
deck = RESULTS / "my_probe_tb.spice"
deck.write_text(f"""* generated by src/check_mine.py - your device line, in a testbench
.lib $PDK_ROOT/sky130A/libs.tech/ngspice/sky130.lib.spice tt
{nfets[0].strip()}
Vgs g 0 1.8
Vds d 0 1.8
.control
op
print i(Vds)
.endc
.end
""")
subprocess.run(["ngspice", "-b", str(deck.relative_to(LAB))], cwd=LAB,
               stdout=open(RESULTS / "my_probe_tb.log", "w"),
               stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL, check=False)

log = (RESULTS / "my_probe_tb.log").read_text()
m = re.search(r"i\(vds\)\s*=\s*(-?[0-9.eE+-]+)", log)
if not m:
    print()
    print("FAIL  ngspice produced no operating point. The first Error line in")
    print("      results/my_probe_tb.log is the real one:")
    for line in log.splitlines():
        if line.startswith("Error") or "could not find" in line:
            print(f"        {line.strip()}")
    sys.exit(1)

i_ua = abs(float(m.group(1))) * 1e6
w = re.search(r"\bW=([^\s]+)", nfets[0]).group(1)
l = re.search(r"\bL=([^\s]+)", nfets[0]).group(1)

print()
print("  YOUR TRANSISTOR")
print(f"    W = {w} um, L = {l} um, V_GS = V_DS = 1.8 V")
print(f"    drain current   {i_ua:10.4f} uA")

if w != REF_W or l != REF_L:
    print()
    print(f"PASS  it netlists, it simulates, and it draws {i_ua:.4f} uA.")
    print(f"      The lab asks for W={REF_W} L={REF_L}, which gives "
          f"{REF_ID_UA:.4f} uA -")
    print(f"      set those if you want to compare against the reference.")
    sys.exit(0)

if abs(i_ua - REF_ID_UA) > TOL_UA:
    print()
    print(f"FAIL  W={REF_W} L={REF_L} should give {REF_ID_UA:.4f} uA and yours "
          f"gives {i_ua:.4f}.")
    print("      Check the four node names on the device line above.")
    sys.exit(1)

print(f"    reference       {REF_ID_UA:10.4f} uA")
print()
print("PASS  you drew a transistor, XSchem turned it into SPICE, and ngspice")
print(f"      answered {i_ua:.4f} uA. That is the whole chain, and it is the")
print("      chain every other lab in this course runs on.")
print()
print(f"  One more thing before you leave. The reference schematic is W=1 and")
print(f"  draws 500.9410 uA. Yours is twice as wide. Twice 500.9410 is")
print(f"  1001.8820, and you measured {i_ua:.4f} - {100*(i_ua/1001.882 - 1):+.2f} %.")
print("  Small, and not zero, and not noise. Lab 04 is entirely about that gap.")
sys.exit(0)
